In [1]:
import pandas as pd
pd.read_csv('個股日成交資訊.csv')

,證券代號,證券名稱,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,0050,元大台灣50,"46,790,503","3,463,425,684",74.95,75.25,72.80,72.80,-2.05,"23,021"
1,0051,元大中型100,"43,172","1,177,199",27.30,27.57,26.75,26.75,-0.52,45
2,0052,富邦科技,"161,425","9,156,750",57.60,57.60,55.35,55.35,-2.35,67
3,0053,元大電子,"35,076","1,163,448",33.36,33.61,32.56,32.69,-0.67,19
4,0054,元大台商50,"27,028","507,569",18.80,19.00,18.64,18.64,-0.36,13
...,...,...,...,...,...,...,...,...,...,...
1108,9944,新麗,"1,463,020","22,024,560",15.60,15.60,14.60,14.65,-0.75,796
1109,9945,潤泰新,"5,262,676","178,768,894",34.20,34.30,33.40,33.40,-0.65,"3,169"
1110,9946,三發地產,"871,456","10,936,770",12.55,12.55,12.55,12.55,-1.35,46
1111,9955,佳龍,"827,246","10,257,476",13.10,13.10,11.85,12.10,-0.50,412
1112,9958,世紀鋼,"10,816,881","868,126,524",81.00,81.80,78.50,79.50,+0.90,"6,743"

In [11]:
#AQI
#下載檔案
#https
import urllib3
import certifi
CSV_URL = "http://opendata.epa.gov.tw/webapi/Data/REWIQA/?$orderby=SiteName&$skip=0&$top=1000&format=csv"
http = urllib3.PoolManager()
response=http.request('GET',CSV_URL)
if response.status == 200:
    print("下載成功")
    with open('空氣品質指標.csv','wb') as file:
        file.write(response.data)
        file.close()
else:
    print("下載失敗")

下載成功

In [12]:
import pandas as pd 
aqiDataFrame = pd.read_csv('空氣品質指標.csv')
aqiDataFrame.dtypes

SiteName        object
County          object
AQI              int64
Pollutant       object
Status          object
SO2            float64
CO              object
CO_8hr         float64
O3              object
O3_8hr         float64
PM10           float64
PM2.5           object
NO2            float64
NOx            float64
NO             float64
WindSpeed      float64
WindDirec      float64
PublishTime     object
PM2.5_AVG        int64
PM10_AVG         int64
SO2_AVG          int64
Longitude      float64
Latitude       float64
SiteId           int64
dtype: object

In [18]:
aqi=aqiDataFrame.reindex(columns=['SiteName','AQI','PM2.5_AVG','PublishTime'])
aqi

   SiteName  AQI  PM2.5_AVG       PublishTime
0        二林   44         14  2020-10-11 12:00
1        三重   25          8  2020-10-11 12:00
2        三義   24          6  2020-10-11 12:00
3        土城   29          6  2020-10-11 12:00
4        士林   34          4  2020-10-11 12:00
..      ...  ...        ...               ...
76       頭份   20          5  2020-10-11 12:00
77       龍潭   33          3  2020-10-11 12:00
78       豐原   32         10  2020-10-11 12:00
79       關山   22          6  2020-10-11 12:00
80       觀音   36         10  2020-10-11 12:00

[81 rows x 4 columns]

In [17]:
aqi['AQI'].min()

19