In [1]:
import pandas as pd
import numpy as np

dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame

#使用dtypes屬性查詢dataFrame所有的欄的資料類型
dataFrame.dtypes

#使用shape屬性查詢欄列數量
dataFrame.shape

#改變欄位索引標籤名稱
dataFrame.columns = dataFrame.loc[0]
dataFrame

#查詢列索引
dataFrame.index

#移除第一列
dataFrame = dataFrame.drop(0)
dataFrame

#查看最後10行
dataFrame.iloc[-10:]

#使用drop刪除最後幾行
dataFrame.drop([371, 372, 373, 374, 375],inplace=True)
dataFrame

#建立新的索引列
#先用shape取出列的數量
rowCount, columnCount = dataFrame.shape
rowCount

#建立新的索引列
dataFrame.index = pd.Index(range(rowCount))
dataFrame

#使用reindex取出想要的欄位
dataFrame1 = dataFrame.reindex(columns=['區域別','年底人口數','土地面積'])
dataFrame1

#使用rename()實體方法改變欄位名稱
dataFrame1 = dataFrame1.rename(columns={'年底人口數':'人口數'})
dataFrame1

0       區域別     人口數     土地面積
0    新北市板橋區  551480  23.1373
1    新北市三重區  387484   16.317
2    新北市中和區  413590   20.144
3    新北市永和區  222585   5.7138
4    新北市新莊區  416524  19.7383
..      ...     ...      ...
365  連江縣北竿鄉    2360      9.9
366  連江縣莒光鄉    1624      4.7
367  連江縣東引鄉    1352      3.8
368    東沙群島      …      2.38
369    南沙群島      …    0.5045

[370 rows x 3 columns]

In [2]:
dataFrame1.dtypes

0
區域別     object
人口數     object
土地面積    object
dtype: object

In [6]:
def format1(x):
    try:
        value = int(x)
    except:
        value = 0
    
    return value

newPopulation = dataFrame1['人口數'].map(format1)
dataFrame1['人口數'] = newPopulation
dataFrame1.dtypes

0
區域別     object
人口數      int64
土地面積    object
dtype: object

In [8]:
def format2(x):
    return float(x)

newArea = dataFrame1['土地面積'].map(format2)
dataFrame1['土地面積'] = newArea
dataFrame1.dtypes

0
區域別      object
人口數       int64
土地面積    float64
dtype: object

In [9]:
dataFrame1

0       區域別     人口數     土地面積
0    新北市板橋區  551480  23.1373
1    新北市三重區  387484  16.3170
2    新北市中和區  413590  20.1440
3    新北市永和區  222585   5.7138
4    新北市新莊區  416524  19.7383
..      ...     ...      ...
365  連江縣北竿鄉    2360   9.9000
366  連江縣莒光鄉    1624   4.7000
367  連江縣東引鄉    1352   3.8000
368    東沙群島       0   2.3800
369    南沙群島       0   0.5045

[370 rows x 3 columns]

In [11]:
dataFrame1[['人口數','土地面積']].apply(lambda x:pd.Series([x.max(),x.min()],index=['最大','最小']))

0      人口數       土地面積
最大  551480  1641.8555
最小       0     0.5045