In [3]:
#直接解析網站的json
import requests
import pandas as pd
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
response = requests.get(url)
data = response.json()
issues=pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

,number,title,labels,state
0,39498,REF: Move agg helpers into apply,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open
1,39497,ENH: Enable parsing of ISO8601-like timestamps...,[],open
2,39496,pandas-dev issue #36111,[],open
3,39495,TST/REF: collect index tests,[],open
4,39494,CI: update for numpy 1.20,[],open
5,39493,ASV: add benchmarks for concatenating and appe...,[],open
6,39492,DOC: Document how encoding errors are handled,[],open
7,39491,TST: Verify plot order of a Series (GH38865),"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
8,39490,Backport PR #39487 on branch 1.2.x (CI: Pin py...,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
9,39489,BUG: GroupBy Aggregation Behavior,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open
10,39488,BUG: setting td64 value into numeric Series in...,[],open
11,39486,BUG: read_excel with openpyxl and missing dime...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
12,39484,BUG: Regression in astype not casting to bytes,"[{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...",open
13,39483,BUG: cumulative functions with ea dtype not ha...,"[{'id': 1817503692, 'node_id': 'MDU6TGFiZWwxOD...",open
14,39482,ERR: Unify error message for bad excel sheetnames,"[{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...",open
15,39481,BUG: Stack creates duplicate column,[],open
16,39480,BUG: Category based on int do not survive a ro...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,39479,BUG: cumsum() shows inconsistent results in nu...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,39478,"BUG: Series[bool].__setitem__(scalar, non_bool)","[{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...",open
19,39474,BUG: Regression cannot create Series with dtyp...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
20,39473,BUG/TST: Address GH28283 calling __finalize__ ...,[],open
21,39467,ENH: read_csv: Warn when dtype or converters c...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
22,39466,"TYP, CLN annotate some variables, remove some ...","[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...",open
23,39465,BUG: DataFrame to_csv compression with 'zip' u...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
24,39464,BUG: Fix sort_values bug that creates unprinta...,[],open
25,39461,BUG: assert_attr_equal with numpy nat or pd.NA,[],open
26,39457,BUG: fixing mixup of bucket and element counts...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
27,39456,CLN: clean error message,"[{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...",open
28,39454,BUG: incorrect casting in DataFrame.append,[],open
29,39453,REF: simplify _get_empty_dtype_and_na,"[{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...",open

In [4]:
#openWeatherMap api
#Taipei:1668341
#Taichung:1668399
#Pingtung:16704818
%matplotlib notebook
import pandas as pd
import matplotlib.pyplot as plt
import requests
url = 'http://api.openweathermap.org/data/2.5/group?id=1668341,1668399,1670481&units=metric&appid=29c4f184354b9889e87f7b494ac86aed'
resp = requests.get(url)
resp
weatherData = resp.json()
weatherDict = {}
lon = []
lat = []
temp = []
humidity = []
name = []
for item in weatherData['list']:
    lon.append(item['coord']['lon'])
    lat.append(item['coord']['lat'])
    temp.append(item['main']['temp'])
    humidity.append(item['main']['humidity'])
    name.append(item['name'])

weatherDict['城市'] = name
weatherDict['緯度'] = lat
weatherDict['經度'] = lon
weatherDict['攝氏'] = temp
weatherDict['溼度'] = humidity
weatherDict
weatherDataFrame = pd.DataFrame(weatherDict,columns=['攝氏', '溼度','緯度', '經度'],index=weatherDict['城市'])
weatherDataFrame

                  攝氏  溼度       緯度        經度
Taipei         22.28  50  25.0478  121.5319
Taichung       21.29  56  24.1469  120.6839
Pingtung City  22.59  46  22.6714  120.4881