In [2]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101, size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name='學號'
scores_pd.columns.name='科目'
scores_pd

科目   國文   英文  數學   地理  歷史
學號
1   100   77  75   64  68
2    81   61  65   59  50
3    56   50  88   58  77
4    90   72  93   67  80
5    65   72  97   52  82
6    90   54  58   79  90
7    72   70  82   86  58
8    65   94  53   97  91
9   100   79  57   88  91
10   78   70  76   72  93
11   78   80  57   95  90
12   79   53  59   96  65
13   53   94  61   63  51
14   79   70  96   65  68
15   81   53  58   73  78
16   73   81  79   78  64
17   78   78  54   86  58
18   64   63  50   74  76
19   64   75  94   59  62
20   59   83  61   95  65
21   83   53  54   82  56
22   62   97  87   51  73
23   73   93  59   64  72
24   67   81  96   55  94
25   58   64  99   92  85
26   71   55  93   75  67
27   89   66  92   61  93
28   95   97  56   53  74
29   56   77  59  100  72
30   96   92  87   70  97
31   95   81  87   90  69
32   92   85  94   63  90
33   58   62  93   53  96
34   64   86  98   53  82
35   78   65  51   72  84
36   86   60  90   77  83
37   94   69  96   75  94
38   98   94  88   54  64
39   99   70  81   93  51
40   50   83  63   88  54
41   96   90  71   66  58
42   54   78  97   56  58
43   54   86  92   99  73
44   88  100  78   75  95
45   57  100  90   85  76
46   91   97  93   71  89
47   57   93  92   78  81
48   74   81  58   55  87
49   93   87  88   99  56
50   90   73  98   71  85

In [3]:
def call(s):
    return pd.Series([s.min(),s.max(),s.median()],index=['最低分','最高分','中間值'])
scores_pd.apply(call)

科目      國文     英文    數學     地理    歷史
最低分   50.0   50.0  50.0   51.0  50.0
最高分  100.0  100.0  99.0  100.0  97.0
中間值   78.0   78.0  84.5   72.5  76.0