In [1]:
#延續example3結果
#這cell是example3所做的功能

import numpy as np
import pandas as pd

dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame.rename(columns={'statistic_yyy':'年','site_id':'區域','people_total':'人口數','area':'土地面積','population_density':'人口密度'},inplace=True)
dataFrame.drop(0,inplace=True)
dataFrame.dropna(thresh=4,inplace=True)
dataFrame.fillna(0, inplace=True)

def transforming(x):
    if x == '… ':
        return 0
    else:
        return x
    
dataFrame = dataFrame.applymap(transforming)
dataFrame.index = dataFrame.index.map(lambda x: f'第{x}筆')
dataFrame

         年      區域     人口數     土地面積   人口密度
第1筆    106  新北市板橋區  551480  23.1373  23835
第2筆    106  新北市三重區  387484   16.317  23747
第3筆    106  新北市中和區  413590   20.144  20532
第4筆    106  新北市永和區  222585   5.7138  38956
第5筆    106  新北市新莊區  416524  19.7383  21102
...    ...     ...     ...      ...    ...
第366筆  106  連江縣北竿鄉    2360      9.9    238
第367筆  106  連江縣莒光鄉    1624      4.7      0
第368筆  106  連江縣東引鄉    1352      3.8      0
第369筆  106    東沙群島       0     2.38      0
第370筆  106    南沙群島       0   0.5045      0

[370 rows x 5 columns]

In [2]:
#範例4現在開始
#搜尋資料
#先檢查資料類型
dataFrame.dtypes

年       object
區域      object
人口數     object
土地面積    object
人口密度    object
dtype: object

In [4]:
#全是字串
#astype()整欄轉型
dataFrame = dataFrame.astype({'人口數':np.int32,'土地面積':np.float32,'人口密度':np.float32})
dataFrame.dtypes

年        object
區域       object
人口數       int32
土地面積    float32
人口密度    float32
dtype: object

In [11]:
#人口數大於300000
frame1=dataFrame[dataFrame['人口數'] >= 300000]
frame1

         年      區域     人口數        土地面積     人口密度
第1筆    106  新北市板橋區  551480   23.137300  23835.0
第2筆    106  新北市三重區  387484   16.316999  23747.0
第3筆    106  新北市中和區  413590   20.143999  20532.0
第5筆    106  新北市新莊區  416524   19.738300  21102.0
第6筆    106  新北市新店區  302089  120.225502   2513.0
第32筆   106  臺北市大安區  309969   11.361400  27283.0
第42筆   106  桃園市桃園區  440840   34.804600  12666.0
第43筆   106  桃園市中壢區  405216   76.519997      0.0
第125筆  106  高雄市三民區  343243   19.786600  17347.0
第132筆  106  高雄市鳳山區  359120   26.759001  13421.0

In [12]:
#人口數大於300000,土地面績小於20
frame2 =frame1[frame1['土地面積'] < 20]
frame2

         年      區域     人口數       土地面積     人口密度
第2筆    106  新北市三重區  387484  16.316999  23747.0
第5筆    106  新北市新莊區  416524  19.738300  21102.0
第32筆   106  臺北市大安區  309969  11.361400  27283.0
第125筆  106  高雄市三民區  343243  19.786600  17347.0

In [18]:
#找出新北市的資料
dataFrame[dataFrame['區域'].str.contains('新北市')]
dataFrame

         年      區域     人口數       土地面積     人口密度
第1筆    106  新北市板橋區  551480  23.137300  23835.0
第2筆    106  新北市三重區  387484  16.316999  23747.0
第3筆    106  新北市中和區  413590  20.143999  20532.0
第4筆    106  新北市永和區  222585   5.713800  38956.0
第5筆    106  新北市新莊區  416524  19.738300  21102.0
...    ...     ...     ...        ...      ...
第366筆  106  連江縣北竿鄉    2360   9.900000    238.0
第367筆  106  連江縣莒光鄉    1624   4.700000      0.0
第368筆  106  連江縣東引鄉    1352   3.800000      0.0
第369筆  106    東沙群島       0   2.380000      0.0
第370筆  106    南沙群島       0   0.504500      0.0

[370 rows x 5 columns]

In [39]:
import re
#.是所有字完，*是0個以上，$最後要是
partern = r'.*永和區$'
dataFrame[dataFrame['區域'].str.match(partern)]

       年      區域     人口數    土地面積     人口密度
第4筆  106  新北市永和區  222585  5.7138  38956.0