In [ ]:
from urllib.request import Request, urlopen
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
url = 'https://goldprice.org/cryptocurrency-price'
heads ={'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}
import_request = Request(url, headers=heads)
web_page_data = urlopen(import_request).read()
web_page_data

In [9]:
import pandas as pd
df = pd.read_html(web_page_data)
dataFrame = df[0]
dataFrame

,Rank,CryptoCurrency,Market Cap.,Price,Circulating Supply,Volume (24h),Change (24h),Price Chart (7d)
0,1,Bitcoin,"$376,715,964,361","$19,761.33",19093393,"$29,365,566,511",-0.29 %,NaN
1,2,Ethereum,"$129,353,311,897","$1,082.74",119676187,"$17,120,640,580",0.31 %,NaN
2,3,Tether,"$65,976,315,866",$1.00,65930930060,"$58,509,019,980",-0.09 %,NaN
3,4,USD Coin,"$55,439,219,388",$1.00,55342154834,"$5,312,521,689",-0.16 %,NaN
4,5,BNB,"$37,272,669,296",$228.48,163276975,"$1,665,523,010",0.74 %,NaN
...,...,...,...,...,...,...,...,...
81,96,Curve DAO,"$399,755,689",$1.02,391958099,"$201,210,248",8.13 %,NaN
82,98,DxChain Token,"$94,790,225",$0.00,0,"$156,923",3.37 %,NaN
83,99,Celo,"$374,890,622",$0.83,450833963,"$21,553,480",0.87 %,NaN
84,100,Aave LINK,"$330,885,424",$25.19,0,"$11,646,285",3.32 %,NaN
85,100,Mina Protocol,"$374,369,810",$0.64,587482904,"$12,840,890",-2.23 %,NaN

In [10]:
dataFrame.drop(columns=['Circulating Supply','Volume (24h)','Price Chart (7d)'],inplace=True)
dataFrame

    Rank CryptoCurrency       Market Cap.       Price Change (24h)
0      1        Bitcoin  $376,715,964,361  $19,761.33      -0.29 %
1      2       Ethereum  $129,353,311,897   $1,082.74       0.31 %
2      3         Tether   $65,976,315,866       $1.00      -0.09 %
3      4       USD Coin   $55,439,219,388       $1.00      -0.16 %
4      5            BNB   $37,272,669,296     $228.48       0.74 %
..   ...            ...               ...         ...          ...
81    96      Curve DAO      $399,755,689       $1.02       8.13 %
82    98  DxChain Token       $94,790,225       $0.00       3.37 %
83    99           Celo      $374,890,622       $0.83       0.87 %
84   100      Aave LINK      $330,885,424      $25.19       3.32 %
85   100  Mina Protocol      $374,369,810       $0.64      -2.23 %

[86 rows x 5 columns]

In [11]:
dataFrame.dtypes

Rank               int64
CryptoCurrency    object
Market Cap.       object
Price             object
Change (24h)      object
dtype: object

In [12]:
dataFrame.rename(columns={'Rank':'名次',
                          'CryptoCurrency':'加密貨幣',
                          'Market Cap.':'市場總市值',
                          'Price':'價格',
                          'Change (24h)':'24小時變化(%)'
                         },inplace=True)
dataFrame

     名次           加密貨幣             市場總市值          價格 24小時變化(%)
0     1        Bitcoin  $376,715,964,361  $19,761.33   -0.29 %
1     2       Ethereum  $129,353,311,897   $1,082.74    0.31 %
2     3         Tether   $65,976,315,866       $1.00   -0.09 %
3     4       USD Coin   $55,439,219,388       $1.00   -0.16 %
4     5            BNB   $37,272,669,296     $228.48    0.74 %
..  ...            ...               ...         ...       ...
81   96      Curve DAO      $399,755,689       $1.02    8.13 %
82   98  DxChain Token       $94,790,225       $0.00    3.37 %
83   99           Celo      $374,890,622       $0.83    0.87 %
84  100      Aave LINK      $330,885,424      $25.19    3.32 %
85  100  Mina Protocol      $374,369,810       $0.64   -2.23 %

[86 rows x 5 columns]

In [16]:
dataFrame['市場總市值'] = dataFrame['市場總市值'].map(lambda value:value[1:])

In [18]:
dataFrame['價格'] = dataFrame['價格'].map(lambda value:value[1:])

In [20]:
dataFrame['24小時變化(%)'] = dataFrame['24小時變化(%)'].map(lambda value:value[:-1])

In [22]:
dataFrame['市場總市值'] = dataFrame['市場總市值'].str.replace(',','')
dataFrame['價格'] = dataFrame['價格'].str.replace(',','')

In [28]:
dataFrame['市場總市值'] = dataFrame['市場總市值'].astype(int)
dataFrame['價格'] = dataFrame['價格'].astype(float).round(2)
dataFrame['24小時變化(%)'] = dataFrame['24小時變化(%)'].astype(float).round(2)

In [30]:
dataFrame

     名次           加密貨幣         市場總市值        價格  24小時變化(%)
0     1        Bitcoin  376715964361  19761.33      -0.29
1     2       Ethereum  129353311897   1082.74       0.31
2     3         Tether   65976315866      1.00      -0.09
3     4       USD Coin   55439219388      1.00      -0.16
4     5            BNB   37272669296    228.48       0.74
..  ...            ...           ...       ...        ...
81   96      Curve DAO     399755689      1.02       8.13
82   98  DxChain Token      94790225      0.00       3.37
83   99           Celo     374890622      0.83       0.87
84  100      Aave LINK     330885424     25.19       3.32
85  100  Mina Protocol     374369810      0.64      -2.23

[86 rows x 5 columns]