In [4]:
import requests

jsonUrl = 'http://ods.railway.gov.tw/tra-ods-web/ods/download/dataResource/8ae4cabf6973990e0169947ed32454b9'
response = requests.get(jsonUrl)
source_json = response.json()

In [5]:
import pandas as pd
frame = pd.DataFrame(source_json)
frame

      trnOpDate staCode gateInComingCnt gateOutGoingCnt
0      20220101    0900            8645            8526
1      20220101    0910             996            1243
2      20220101    0920            1369            1711
3      20220101    0930            3663            4535
4      20220101    0940            1532            1845
...         ...     ...             ...             ...
36099  20220601    7360            2088            2263
36100  20220601    7361              17              40
36101  20220601    7362              31              30
36102  20220601    7380             509             508
36103  20220601    7390             354             369

[36104 rows x 4 columns]

In [7]:
staCode_url = 'http://ods.railway.gov.tw/tra-ods-web/ods/download/dataResource/0518b833e8964d53bfea3f7691aea0ee'
response = requests.get(staCode_url)
staCode_json = response.json()

In [9]:
staCode_frame = pd.DataFrame(staCode_json,columns=['stationCode', 'stationName','stationAddrTw'])
staCode_frame

    stationCode stationName                      stationAddrTw
0          0900          基隆              基隆市中山區民治里1鄰中山一路16之 1號
1          0910          三坑                 基隆市仁愛區德厚里龍安街 206 號
2          0920          八堵                 基隆市暖暖區八南里八堵路 142 號
3          0930          七堵                   基隆市七堵區長興里東新街 2 號
4          0940          百福              基隆市七堵區堵南里明德三路 1 之 1 號
..          ...         ...                                ...
237        7360          瑞芳                新北市瑞芳區龍潭里明燈路三段 82 號
238        7361         海科館                          基隆市中正區長潭里
239        7362         八斗子  基隆市中正區砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房)
240        7380         四腳亭                  新北市瑞芳區吉慶里中央路 65 號
241        7390          暖暖                  基隆市暖暖區暖暖里暖暖街 51 號

[242 rows x 3 columns]

In [11]:
merge_result = pd.merge(frame,staCode_frame,left_on='staCode',right_on='stationCode',how='left')
merge_result

,trnOpDate,staCode,gateInComingCnt,gateOutGoingCnt,stationCode,stationName,stationAddrTw
0,20220101,0900,8645,8526,0900,基隆,基隆市中山區民治里1鄰中山一路16之 1號
1,20220101,0910,996,1243,0910,三坑,基隆市仁愛區德厚里龍安街 206 號
2,20220101,0920,1369,1711,0920,八堵,基隆市暖暖區八南里八堵路 142 號
3,20220101,0930,3663,4535,0930,七堵,基隆市七堵區長興里東新街 2 號
4,20220101,0940,1532,1845,0940,百福,基隆市七堵區堵南里明德三路 1 之 1 號
...,...,...,...,...,...,...,...
36099,20220601,7360,2088,2263,7360,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號
36100,20220601,7361,17,40,7361,海科館,基隆市中正區長潭里
36101,20220601,7362,31,30,7362,八斗子,基隆市中正區砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房)
36102,20220601,7380,509,508,7380,四腳亭,新北市瑞芳區吉慶里中央路 65 號
36103,20220601,7390,354,369,7390,暖暖,基隆市暖暖區暖暖里暖暖街 51 號

In [12]:
merge_result = merge_result[['trnOpDate','stationName','stationAddrTw','gateInComingCnt','gateOutGoingCnt']]
merge_result

,trnOpDate,stationName,stationAddrTw,gateInComingCnt,gateOutGoingCnt
0,20220101,基隆,基隆市中山區民治里1鄰中山一路16之 1號,8645,8526
1,20220101,三坑,基隆市仁愛區德厚里龍安街 206 號,996,1243
2,20220101,八堵,基隆市暖暖區八南里八堵路 142 號,1369,1711
3,20220101,七堵,基隆市七堵區長興里東新街 2 號,3663,4535
4,20220101,百福,基隆市七堵區堵南里明德三路 1 之 1 號,1532,1845
...,...,...,...,...,...
36099,20220601,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,2088,2263
36100,20220601,海科館,基隆市中正區長潭里,17,40
36101,20220601,八斗子,基隆市中正區砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),31,30
36102,20220601,四腳亭,新北市瑞芳區吉慶里中央路 65 號,509,508
36103,20220601,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,354,369

In [14]:
merge_result.columns = ['日期','站名','站址','進站人數','出站人數']
merge_result

             日期   站名                                 站址  進站人數  出站人數
0      20220101   基隆              基隆市中山區民治里1鄰中山一路16之 1號  8645  8526
1      20220101   三坑                 基隆市仁愛區德厚里龍安街 206 號   996  1243
2      20220101   八堵                 基隆市暖暖區八南里八堵路 142 號  1369  1711
3      20220101   七堵                   基隆市七堵區長興里東新街 2 號  3663  4535
4      20220101   百福              基隆市七堵區堵南里明德三路 1 之 1 號  1532  1845
...         ...  ...                                ...   ...   ...
36099  20220601   瑞芳                新北市瑞芳區龍潭里明燈路三段 82 號  2088  2263
36100  20220601  海科館                          基隆市中正區長潭里    17    40
36101  20220601  八斗子  基隆市中正區砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房)    31    30
36102  20220601  四腳亭                  新北市瑞芳區吉慶里中央路 65 號   509   508
36103  20220601   暖暖                  基隆市暖暖區暖暖里暖暖街 51 號   354   369

[36104 rows x 5 columns]