In [1]:
import csv
import pandas as pd

with open('新北市食品工廠清冊.csv','r',encoding='utf-8') as file:    
    rows = csv.reader(file)
    datalist = [row for row in rows]
    title=datalist.pop(0)

dataFrame = pd.DataFrame(datalist,columns=title)
dataFrame

,"﻿""Name_Ins""",No,Address,tax_ID_number,twd97X,twd97Y,wgs84aX,wgs84aY
0,鴻輝食品廠,99611344,新北市新莊區新莊路四九三巷四弄一一號,35567635,295271.81,2769474.82,121.448618091317,25.0327031220478
1,廣達香食品股份有限公司,99604192,新北市新莊區化成路三八二巷一八號,35549807,297142.6,2771386.31,121.467221414508,25.04990297127
2,順發糧食行,99613990,新北市板橋區縣民大道一段二八一號,33305209,296479.77,2766976.61,121.460503814584,25.0101125037041
3,台灣塩野香料股份有限公司,99600477,新北市新莊區化成路二一九號,03561504,296988.9,2771035.63,121.465686254094,25.0467418103903
4,圓金釀造食品股份有限公司,99606467,新北市新莊區新樹路二六八巷二二號,35427115,293506.24,2767400.65,121.431057250618,25.0140290966789
...,...,...,...,...,...,...,...,...
1227,元茂農產企業股份有限公司二廠,65007117,新北市新莊區五權一路3號之2(1樓),54029004,296144.93,2773120.75,121.457392108499,25.0655922866113
1228,萬寶客股份有限公司,65007172,新北市蘆洲區國道路2段25號3樓,54684830,297878.58,2774033.85,121.474607439816,25.073781780003
1229,昆帝食品有限公司,65007211,新北市五股區五權三路47號(1樓),66612826,296033.56,2773399.99,121.456297513558,25.0681166276338
1230,嚐鱻食品有限公司板橋廠,65007246,新北市板橋區和平路14巷30號1、2樓,27798177,296616.53,2764961.33,121.461790748796,24.9919141131402
1231,崴欣國際有限公司,65007247,新北市中和區中山路二段448號3樓,24456211,299358.5,2766359.34,121.489002297811,25.0044487093875

In [2]:
dataFrame.dtypes

﻿"Name_Ins"      object
No               object
Address          object
tax_ID_number    object
twd97X           object
twd97Y           object
wgs84aX          object
wgs84aY          object
dtype: object

In [9]:
dataFrame[["No", "Address"]]

            No              Address
0     99611344   新北市新莊區新莊路四九三巷四弄一一號
1     99604192     新北市新莊區化成路三八二巷一八號
2     99613990     新北市板橋區縣民大道一段二八一號
3     99600477        新北市新莊區化成路二一九號
4     99606467     新北市新莊區新樹路二六八巷二二號
...        ...                  ...
1227  65007117   新北市新莊區五權一路3號之2(1樓)
1228  65007172     新北市蘆洲區國道路2段25號3樓
1229  65007211    新北市五股區五權三路47號(1樓)
1230  65007246  新北市板橋區和平路14巷30號1、2樓
1231  65007247    新北市中和區中山路二段448號3樓

[1232 rows x 2 columns]

In [13]:
import requests
url = 'https://data.taipei/api/dataset/a0f33c38-bd7d-44bc-a33d-54a332ffd8f1/resource/98ae9fc8-092c-4898-9953-7758bf3784b7/download'
response = requests.get(url,stream=True)
with open('a.csv', 'wb') as fd:
    for chunk in response.iter_content(chunk_size=128):
        fd.write(chunk)

In [18]:
with open('a.csv','r',encoding='big5') as file:    
    rows = csv.reader(file)
    datalist = [row for row in rows]
    title=datalist.pop(0)

dataFrame = pd.DataFrame(datalist,columns=title)
dataFrame

        役政單位                地址          連絡電話
0   臺北市政府兵役局    臺北市羅斯福路4段92號9樓  (02)23654361
1      松山區公所    臺北市八德路4段692號7樓  (02)87878787
2      信義區公所     臺北市信義路5段15號6樓  (02)27239777
3      大安區公所    臺北市新生南路2段86號8樓  (02)23511711
4      中山區公所      臺北市松江路367號5樓  (02)25031369
5      中正區公所   臺北市忠孝東路一段108號8樓  (02)23416721
6      大同區公所       臺北市昌吉街57號4樓  (02)25975323
7      萬華區公所  臺北市和平西路三段120號11樓  (02)23064468
8      文山區公所    臺北市木柵路3段220號8樓  (02)29365522
9      南港區公所    臺北市南港路1段360號8樓  (02)27831343
10     內湖區公所    臺北市民權東路6段99號4樓  (02)27925828
11     士林區公所      臺北市中正路439號9樓  (02)28826200
12     北投區公所       臺北市新市街30號4樓  (02)28912105