In [8]:
import numpy as np
import pandas as pd

dataFrame = pd.read_csv('world.csv')
dataFrame.dtypes

ID                  int64
iso_code           object
洲名                 object
國家                 object
日期                 object
總確診數                int64
新增確診數               int64
七天移動平均新增確診數       float64
總死亡數                int64
新增死亡數               int64
七天移動平均新增死亡數       float64
每百萬人確診數           float64
每百萬人死亡數           float64
傳染率               float64
新增檢驗件數              int64
總檢驗件數               int64
每千人檢驗件數           float64
七天移動平均新增檢驗件數      float64
陽性率               float64
每確診案例相對檢驗數量       float64
疫苗總接種總劑數            int64
疫苗總接種人數             int64
疫苗新增接種劑數            int64
七天移動平均疫苗新增接種劑數    float64
每百人接種疫苗劑數         float64
每百人接種疫苗人數         float64
疫情控管指數            float64
總人口數                int64
中位數年紀             float64
70歲以上人口比例         float64
平均壽命              float64
解除隔離數               int64
解封指數              float64
dtype: object

In [4]:
dataFrame.shape

(179883, 33)

In [9]:
dataFrame = dataFrame.reindex(columns=['洲名','國家','日期','總確診數','新增確診數','新增死亡數','總人口數'])
dataFrame.tail(20)

        洲名   國家          日期    總確診數  新增確診數  新增死亡數      總人口數
179863  非洲  辛巴威  2022-03-30  246182    140      1  15092171
179864  非洲  辛巴威  2022-03-31  246286    104      4  15092171
179865  非洲  辛巴威  2022-04-01  246414    128      0  15092171
179866  非洲  辛巴威  2022-04-02  246481     67      2  15092171
179867  非洲  辛巴威  2022-04-03  246525     44      0  15092171
179868  非洲  辛巴威  2022-04-04  246612     87      5  15092171
179869  非洲  辛巴威  2022-04-05  246744    132      0  15092171
179870  非洲  辛巴威  2022-04-06  246803     59      2  15092171
179871  非洲  辛巴威  2022-04-07  246870     67      2  15092171
179872  非洲  辛巴威  2022-04-08  246925     55      2  15092171
179873  非洲  辛巴威  2022-04-09  246925      0      0  15092171
179874  非洲  辛巴威  2022-04-10  246958     33      0  15092171
179875  非洲  辛巴威  2022-04-11  247010     52      3  15092171
179876  非洲  辛巴威  2022-04-12  247094     84      0  15092171
179877  非洲  辛巴威  2022-04-13  247160     66      0  15092171
179878  非洲  辛巴威  2022-04-14  247208     48      2  15092171
179879  非洲  辛巴威  2022-04-15  247237     29      0  15092171
179880  非洲  辛巴威  2022-04-16  247237      0      0  15092171
179881  非洲  辛巴威  2022-04-17  247278     41      1  15092171
179882  非洲  辛巴威  2022-04-18  247297     19      1  15092171