In [6]:
import numpy as np
import pandas as pd
result=pd.read_csv('ex6.csv')
result.info()
result

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
one      10000 non-null float64
two      10000 non-null float64
three    10000 non-null float64
four     10000 non-null float64
key      10000 non-null object
dtypes: float64(4), object(1)
memory usage: 390.8+ KB

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [8]:
result.index.name = '編號'
result

           one       two     three      four key
編號
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [9]:
result[:20]

         one       two     three      four key
編號
0   0.467976 -0.038649 -0.295344 -1.824726   L
1  -0.358893  1.404453  0.704965 -0.200638   B
2  -0.501840  0.659254 -0.421691 -0.057688   G
3   0.204886  1.074134  1.388361 -0.982404   R
4   0.354628 -0.133116  0.283763 -0.837063   Q
5   1.817480  0.742273  0.419395 -2.251035   Q
6  -0.776764  0.935518 -0.332872 -1.875641   U
7  -0.913135  1.530624 -0.572657  0.477252   K
8   0.358480 -0.497572 -0.367016  0.507702   S
9  -1.740877 -1.160417 -1.637830  2.172201   G
10  0.240564 -0.328249  1.252155  1.072796   8
11  0.764018  1.165476 -0.639544  1.495258   R
12  0.571035 -0.310537  0.582437 -0.298765   1
13  2.317658  0.430710 -1.334216  0.199679   P
14  1.547771 -1.119753 -2.277634  0.329586   J
15 -1.310608  0.401719 -1.000987  1.156708   E
16 -0.088496  0.634712  0.153324  0.415335   B
17 -0.018663 -0.247487 -1.446522  0.750938   A
18 -0.070127 -1.579097  0.120892  0.671432   F
19 -0.194678 -0.492039  2.359605  0.319810   H

In [10]:
result[-20:]

           one       two     three      four key
編號
9980 -0.595349  0.001781 -1.423355 -1.458477   M
9981  1.392170 -1.396560 -1.425306 -0.847535   H
9982 -0.896029 -0.152287  1.924483  0.365184   6
9983 -2.274642 -0.901874  1.500352  0.996541   N
9984 -0.301898  1.019906  1.102160  2.624526   I
9985 -2.548389 -0.585374  1.496201 -0.718815   D
9986 -0.064588  0.759292 -1.568415 -0.420933   E
9987 -0.143365 -1.111760 -1.815581  0.435274   2
9988 -0.070412 -1.055921  0.338017 -0.440763   X
9989  0.649148  0.994273 -1.384227  0.485120   Q
9990 -0.370769  0.404356 -1.051628 -1.050899   8
9991 -0.409980  0.155627 -0.818990  1.277350   W
9992  0.301214 -1.111203  0.668258  0.671922   A
9993  1.821117  0.416445  0.173874  0.505118   X
9994  0.068804  1.322759  0.802346  0.223618   H
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

In [14]:
newResult = result.reset_index().set_index(['key', '編號'])
newResult

               one       two     three      four
key 編號
L   0     0.467976 -0.038649 -0.295344 -1.824726
B   1    -0.358893  1.404453  0.704965 -0.200638
G   2    -0.501840  0.659254 -0.421691 -0.057688
R   3     0.204886  1.074134  1.388361 -0.982404
Q   4     0.354628 -0.133116  0.283763 -0.837063
...            ...       ...       ...       ...
L   9995  2.311896 -0.417070 -1.409599 -0.515821
E   9996 -0.479893 -0.650419  0.745152 -0.646038
K   9997  0.523331  0.787112  0.486066  1.093156
G   9998 -0.362559  0.598894 -1.843201  0.887292
0   9999 -0.096376 -1.012999 -0.657431 -0.573315

[10000 rows x 4 columns]

In [16]:
newSerial = newResult['one']
newSerial

key  編號
L    0       0.467976
B    1      -0.358893
G    2      -0.501840
R    3       0.204886
Q    4       0.354628
               ...
L    9995    2.311896
E    9996   -0.479893
K    9997    0.523331
G    9998   -0.362559
0    9999   -0.096376
Name: one, Length: 10000, dtype: float64

In [20]:
newSerial.sort_index(level='key',inplace=True)
newSerial.index

MultiIndex([('0',  101),
            ('0',  142),
            ('0',  168),
            ('0',  197),
            ('0',  429),
            ('0',  453),
            ('0',  654),
            ('0',  776),
            ('0',  784),
            ('0', 1094),
            ...
            ('Z', 9554),
            ('Z', 9558),
            ('Z', 9584),
            ('Z', 9634),
            ('Z', 9697),
            ('Z', 9774),
            ('Z', 9878),
            ('Z', 9901),
            ('Z', 9942),
            ('Z', 9972)],
           names=['key', '編號'], length=10000)

In [21]:
newSerial.unstack()

編號,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
key,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.096376
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.370769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.301214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B,NaN,-0.358893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.479893,NaN,NaN,NaN
F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
G,NaN,NaN,-0.50184,NaN,NaN,NaN,NaN,NaN,NaN,-1.740877,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.362559,NaN
H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.068804,NaN,NaN,NaN,NaN,NaN
I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.913135,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.523331,NaN,NaN
L,0.467976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.311896,NaN,NaN,NaN,NaN
M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q,NaN,NaN,NaN,NaN,0.354628,1.81748,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
R,NaN,NaN,NaN,0.204886,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.35848,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
U,NaN,NaN,NaN,NaN,NaN,NaN,-0.776764,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.40998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.821117,NaN,NaN,NaN,NaN,NaN,NaN
Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
newSerial.sum()

457.5016080420036

In [26]:
newSerial.sum(level='key')

key
0     1.665408
1    11.425734
2   -12.027358
3    42.100302
4     3.369031
5   -21.339628
6    23.546088
7    13.590415
8    -0.013861
9     9.765136
A    38.897269
B    15.440654
C     7.088463
D     2.301488
E     7.847879
F    26.900181
G   -17.480410
H    -7.082552
I     8.148561
J    16.241878
K    51.695215
L    17.545360
M     1.186659
N    14.999531
O   -10.002795
P     9.425316
Q   -13.331859
R    38.933116
S    23.171948
T    48.116511
U    16.968534
V    -3.523774
W    49.312915
X    27.783672
Y    16.990201
Z    -2.153618
Name: one, dtype: float64