In [1]:
import pandas as pd
import numpy as np

dataFrame=pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame

,statistic_yyy,site_id,people_total,area,population_density
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [2]:
dataFrame.dtypes

statistic_yyy         object
site_id               object
people_total          object
area                  object
population_density    object
dtype: object

In [3]:
dataFrame.shape

(376, 5)

In [4]:
dataFrame.columns = dataFrame.loc[0]
dataFrame

,統計年,區域別,年底人口數,土地面積,人口密度
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [5]:
dataFrame.drop(0,inplace=True)
dataFrame

,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
5,106,新北市新莊區,416524,19.7383,21102
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [6]:
dataFrame.tail()

0    統計年                                                區域別 年底人口數 土地面積 人口密度
371  NaN                                                NaN   NaN  NaN  NaN
372  NaN                           說明：1.人口密度係指每單位土地面積內之人口數。   NaN  NaN  NaN
373  NaN  2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里)   NaN  NaN  NaN
374  NaN           ，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。   NaN  NaN  NaN
375  NaN           3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。   NaN  NaN  NaN

In [7]:
dataFrame.drop([371, 372, 373, 374, 375],inplace=True)

In [8]:
dataFrame

0    統計年     區域別   年底人口數     土地面積   人口密度
1    106  新北市板橋區  551480  23.1373  23835
2    106  新北市三重區  387484   16.317  23747
3    106  新北市中和區  413590   20.144  20532
4    106  新北市永和區  222585   5.7138  38956
5    106  新北市新莊區  416524  19.7383  21102
..   ...     ...     ...      ...    ...
366  106  連江縣北竿鄉    2360      9.9    238
367  106  連江縣莒光鄉    1624      4.7    346
368  106  連江縣東引鄉    1352      3.8    356
369  106    東沙群島      …      2.38     …
370  106    南沙群島      …    0.5045     …

[370 rows x 5 columns]

In [10]:
rowCout, columnCount = dataFrame.shape
print(rowCout)
print(columnCount)

370
5

In [11]:
dataFrame.index = range(370)
dataFrame

0    統計年     區域別   年底人口數     土地面積   人口密度
0    106  新北市板橋區  551480  23.1373  23835
1    106  新北市三重區  387484   16.317  23747
2    106  新北市中和區  413590   20.144  20532
3    106  新北市永和區  222585   5.7138  38956
4    106  新北市新莊區  416524  19.7383  21102
..   ...     ...     ...      ...    ...
365  106  連江縣北竿鄉    2360      9.9    238
366  106  連江縣莒光鄉    1624      4.7    346
367  106  連江縣東引鄉    1352      3.8    356
368  106    東沙群島      …      2.38     …
369  106    南沙群島      …    0.5045     …

[370 rows x 5 columns]

In [12]:
newDataFrame = dataFrame.reindex(columns=['區域別','年底人口數','土地面積'])
newDataFrame

0       區域別   年底人口數     土地面積
0    新北市板橋區  551480  23.1373
1    新北市三重區  387484   16.317
2    新北市中和區  413590   20.144
3    新北市永和區  222585   5.7138
4    新北市新莊區  416524  19.7383
..      ...     ...      ...
365  連江縣北竿鄉    2360      9.9
366  連江縣莒光鄉    1624      4.7
367  連江縣東引鄉    1352      3.8
368    東沙群島      …      2.38
369    南沙群島      …    0.5045

[370 rows x 3 columns]

In [17]:
newDataFrame.rename(columns={'年底人口數':'人口數'},inplace=True)

In [18]:
newDataFrame

0       區域別     人口數     土地面積
0    新北市板橋區  551480  23.1373
1    新北市三重區  387484   16.317
2    新北市中和區  413590   20.144
3    新北市永和區  222585   5.7138
4    新北市新莊區  416524  19.7383
..      ...     ...      ...
365  連江縣北竿鄉    2360      9.9
366  連江縣莒光鄉    1624      4.7
367  連江縣東引鄉    1352      3.8
368    東沙群島      …      2.38
369    南沙群島      …    0.5045

[370 rows x 3 columns]

In [20]:
newDataFrame = newDataFrame.iloc[:-2]

In [21]:
newDataFrame

0       區域別     人口數     土地面積
0    新北市板橋區  551480  23.1373
1    新北市三重區  387484   16.317
2    新北市中和區  413590   20.144
3    新北市永和區  222585   5.7138
4    新北市新莊區  416524  19.7383
..      ...     ...      ...
363  金門縣烏坵鄉     685      1.2
364  連江縣南竿鄉    7544     10.4
365  連江縣北竿鄉    2360      9.9
366  連江縣莒光鄉    1624      4.7
367  連江縣東引鄉    1352      3.8

[368 rows x 3 columns]

In [23]:
newDataFrame['人口數'] = newDataFrame['人口數'].map(lambda x: int(x))

<ipython-input-23-6c0e5a0d9f27>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newDataFrame['人口數'] = newDataFrame['人口數'].map(lambda x: int(x))

In [26]:
newDataFrame['土地面積'] = newDataFrame['土地面積'].map(lambda x: float(x))

<ipython-input-26-ac22688e99d2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newDataFrame['土地面積'] = newDataFrame['土地面積'].map(lambda x: float(x))

In [28]:
newDataFrame.dtypes

0
區域別      object
人口數       int64
土地面積    float64
dtype: object

In [29]:
newDataFrame

0       區域別     人口數     土地面積
0    新北市板橋區  551480  23.1373
1    新北市三重區  387484  16.3170
2    新北市中和區  413590  20.1440
3    新北市永和區  222585   5.7138
4    新北市新莊區  416524  19.7383
..      ...     ...      ...
363  金門縣烏坵鄉     685   1.2000
364  連江縣南竿鄉    7544  10.4000
365  連江縣北竿鄉    2360   9.9000
366  連江縣莒光鄉    1624   4.7000
367  連江縣東引鄉    1352   3.8000

[368 rows x 3 columns]

In [32]:
finalDataFrame = newDataFrame.set_index('區域別')
finalDataFrame

0          人口數     土地面積
區域別
新北市板橋區  551480  23.1373
新北市三重區  387484  16.3170
新北市中和區  413590  20.1440
新北市永和區  222585   5.7138
新北市新莊區  416524  19.7383
...        ...      ...
金門縣烏坵鄉     685   1.2000
連江縣南竿鄉    7544  10.4000
連江縣北竿鄉    2360   9.9000
連江縣莒光鄉    1624   4.7000
連江縣東引鄉    1352   3.8000

[368 rows x 2 columns]

In [34]:
finalDataFrame.apply(lambda x:pd.Series([x.max(), x.min()]))

0     人口數       土地面積
0  551480  1641.8555
1     685     0.8803