In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.825678 -0.912719
1    a  two -1.389770  0.750655
2    b  one -0.276574  0.718488
3    b  two -1.019010  0.050866
4    a  one  2.317692  0.276038

In [2]:
grouped = df['data1'].groupby(df['key1'])
grouped

In [3]:
grouped.mean()

key1
a    0.584533
b   -0.647792
Name: data1, dtype: float64

In [7]:
means=df['data1'].groupby([df['key1'],df['key2']]).mean()
means

key1  key2
a     one     1.571685
      two    -1.389770
b     one    -0.276574
      two    -1.019010
Name: data1, dtype: float64

In [8]:
means.unstack()

key2       one      two
key1
a     1.571685 -1.38977
b    -0.276574 -1.01901

In [9]:
states = np.array(['台北','台中','台中','台北','台北'])
years = np.array([2005, 2005, 2006, 2005, 2006])
df['data1'].groupby([states, years]).mean()

台中  2005   -1.389770
    2006   -0.276574
台北  2005   -0.096666
    2006    2.317692
Name: data1, dtype: float64

In [10]:
df.groupby('key1').mean()

         data1     data2
key1
a     0.584533  0.037991
b    -0.647792  0.384677

In [11]:
df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.100872 -0.238103
1    a  two  1.058258 -1.014298
2    b  one  0.673445 -0.388994
3    b  two -1.355183  0.625355
4    a  one -0.372116 -1.152169

In [12]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)

a
  key1 key2     data1     data2
0    a  one  0.100872 -0.238103
1    a  two  1.058258 -1.014298
4    a  one -0.372116 -1.152169
b
  key1 key2     data1     data2
2    b  one  0.673445 -0.388994
3    b  two -1.355183  0.625355

In [14]:
pieces=dict(list(df.groupby('key1')))
pieces

{'a':   key1 key2     data1     data2
 0    a  one  0.100872 -0.238103
 1    a  two  1.058258 -1.014298
 4    a  one -0.372116 -1.152169,
 'b':   key1 key2     data1     data2
 2    b  one  0.673445 -0.388994
 3    b  two -1.355183  0.625355}

In [15]:
pieces

{'a':   key1 key2     data1     data2
 0    a  one  0.100872 -0.238103
 1    a  two  1.058258 -1.014298
 4    a  one -0.372116 -1.152169,
 'b':   key1 key2     data1     data2
 2    b  one  0.673445 -0.388994
 3    b  two -1.355183  0.625355}

In [16]:
pieces['a']

  key1 key2     data1     data2
0    a  one  0.100872 -0.238103
1    a  two  1.058258 -1.014298
4    a  one -0.372116 -1.152169

In [17]:
import numpy as np
import pandas as pd

tips = pd.read_csv('tips.csv')
tips

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [18]:
tips.dtypes

total_bill    float64
tip           float64
smoker         object
day            object
time           object
size            int64
dtype: object

In [19]:
tips.shape

(244, 6)

In [20]:
tips.columns =['總票價', '小費', '吸煙者', '日期', '時間', '大小']
tips

       總票價    小費  吸煙者    日期      時間  大小
0    16.99  1.01   No   Sun  Dinner   2
1    10.34  1.66   No   Sun  Dinner   3
2    21.01  3.50   No   Sun  Dinner   3
3    23.68  3.31   No   Sun  Dinner   2
4    24.59  3.61   No   Sun  Dinner   4
..     ...   ...  ...   ...     ...  ..
239  29.03  5.92   No   Sat  Dinner   3
240  27.18  2.00  Yes   Sat  Dinner   2
241  22.67  2.00  Yes   Sat  Dinner   2
242  17.82  1.75   No   Sat  Dinner   2
243  18.78  3.00   No  Thur  Dinner   2

[244 rows x 6 columns]

In [22]:
tips['小費比例'] = tips['小費'] / tips['總票價']
tips

       總票價    小費  吸煙者    日期      時間  大小      小費比例
0    16.99  1.01   No   Sun  Dinner   2  0.059447
1    10.34  1.66   No   Sun  Dinner   3  0.160542
2    21.01  3.50   No   Sun  Dinner   3  0.166587
3    23.68  3.31   No   Sun  Dinner   2  0.139780
4    24.59  3.61   No   Sun  Dinner   4  0.146808
..     ...   ...  ...   ...     ...  ..       ...
239  29.03  5.92   No   Sat  Dinner   3  0.203927
240  27.18  2.00  Yes   Sat  Dinner   2  0.073584
241  22.67  2.00  Yes   Sat  Dinner   2  0.088222
242  17.82  1.75   No   Sat  Dinner   2  0.098204
243  18.78  3.00   No  Thur  Dinner   2  0.159744

[244 rows x 7 columns]

In [25]:
tips['小費比例1'] = tips.apply(lambda x:x['小費']/x['總票價'],axis=1)

總票價         16.99
小費           1.01
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.059447
小費比例1         NaN
Name: 0, dtype: object
總票價         10.34
小費           1.66
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.160542
小費比例1         NaN
Name: 1, dtype: object
總票價         21.01
小費            3.5
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.166587
小費比例1         NaN
Name: 2, dtype: object
總票價        23.68
小費          3.31
吸煙者           No
日期           Sun
時間        Dinner
大小             2
小費比例     0.13978
小費比例1        NaN
Name: 3, dtype: object
總票價         24.59
小費           3.61
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.146808
小費比例1         NaN
Name: 4, dtype: object
總票價        25.29
小費          4.71
吸煙者           No
日期           Sun
時間        Dinner
大小             4
小費比例     0.18624
小費比例1        NaN
Name: 5, dtype: object
總票價         8.77
小費           2.0
吸煙者           No
日期           Sun
時間        Dinner
大小             2
小費比例     0.22805
小費比例1        NaN
Name: 6, dtype: object
總票價         26.88
小費           3.12
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.116071
小費比例1         NaN
Name: 7, dtype: object
總票價         15.04
小費           1.96
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.130319
小費比例1         NaN
Name: 8, dtype: object
總票價         14.78
小費           3.23
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.218539
小費比例1         NaN
Name: 9, dtype: object
總票價         10.27
小費           1.71
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.166504
小費比例1         NaN
Name: 10, dtype: object
總票價         35.26
小費            5.0
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.141804
小費比例1         NaN
Name: 11, dtype: object
總票價         15.42
小費           1.57
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.101816
小費比例1         NaN
Name: 12, dtype: object
總票價         18.43
小費            3.0
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.162778
小費比例1         NaN
Name: 13, dtype: object
總票價         14.83
小費           3.02
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.203641
小費比例1         NaN
Name: 14, dtype: object
總票價        21.58
小費          3.92
吸煙者           No
日期           Sun
時間        Dinner
大小             2
小費比例     0.18165
小費比例1        NaN
Name: 15, dtype: object
總票價         10.33
小費           1.67
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.161665
小費比例1         NaN
Name: 16, dtype: object
總票價         16.29
小費           3.71
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.227747
小費比例1         NaN
Name: 17, dtype: object
總票價         16.97
小費            3.5
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.206246
小費比例1         NaN
Name: 18, dtype: object
總票價         20.65
小費           3.35
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.162228
小費比例1         NaN
Name: 19, dtype: object
總票價         17.92
小費           4.08
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.227679
小費比例1         NaN
Name: 20, dtype: object
總票價         20.29
小費           2.75
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.135535
小費比例1         NaN
Name: 21, dtype: object
總票價         15.77
小費           2.23
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.141408
小費比例1         NaN
Name: 22, dtype: object
總票價         39.42
小費           7.58
吸煙者            No
日期            Sat
時間         Dinner
大小              4
小費比例     0.192288
小費比例1         NaN
Name: 23, dtype: object
總票價         19.82
小費           3.18
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.160444
小費比例1         NaN
Name: 24, dtype: object
總票價         17.81
小費           2.34
吸煙者            No
日期            Sat
時間         Dinner
大小              4
小費比例     0.131387
小費比例1         NaN
Name: 25, dtype: object
總票價         13.37
小費            2.0
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.149589
小費比例1         NaN
Name: 26, dtype: object
總票價         12.69
小費            2.0
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.157604
小費比例1         NaN
Name: 27, dtype: object
總票價          21.7
小費            4.3
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.198157
小費比例1         NaN
Name: 28, dtype: object
總票價         19.65
小費            3.0
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.152672
小費比例1         NaN
Name: 29, dtype: object
總票價          9.55
小費           1.45
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.151832
小費比例1         NaN
Name: 30, dtype: object
總票價        18.35
小費           2.5
吸煙者           No
日期           Sat
時間        Dinner
大小             4
小費比例     0.13624
小費比例1        NaN
Name: 31, dtype: object
總票價         15.06
小費            3.0
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.199203
小費比例1         NaN
Name: 32, dtype: object
總票價         20.69
小費           2.45
吸煙者            No
日期            Sat
時間         Dinner
大小              4
小費比例     0.118415
小費比例1         NaN
Name: 33, dtype: object
總票價         17.78
小費           3.27
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.183915
小費比例1         NaN
Name: 34, dtype: object
總票價         24.06
小費            3.6
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.149626
小費比例1         NaN
Name: 35, dtype: object
總票價         16.31
小費            2.0
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.122624
小費比例1         NaN
Name: 36, dtype: object
總票價         16.93
小費           3.07
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.181335
小費比例1         NaN
Name: 37, dtype: object
總票價         18.69
小費           2.31
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.123596
小費比例1         NaN
Name: 38, dtype: object
總票價         31.27
小費            5.0
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.159898
小費比例1         NaN
Name: 39, dtype: object
總票價         16.04
小費           2.24
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.139651
小費比例1         NaN
Name: 40, dtype: object
總票價         17.46
小費           2.54
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.145475
小費比例1         NaN
Name: 41, dtype: object
總票價         13.94
小費           3.06
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.219512
小費比例1         NaN
Name: 42, dtype: object
總票價          9.68
小費           1.32
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.136364
小費比例1         NaN
Name: 43, dtype: object
總票價          30.4
小費            5.6
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.184211
小費比例1         NaN
Name: 44, dtype: object
總票價         18.29
小費            3.0
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.164024
小費比例1         NaN
Name: 45, dtype: object
總票價         22.23
小費            5.0
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.224921
小費比例1         NaN
Name: 46, dtype: object
總票價          32.4
小費            6.0
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.185185
小費比例1         NaN
Name: 47, dtype: object
總票價         28.55
小費           2.05
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.071804
小費比例1         NaN
Name: 48, dtype: object
總票價         18.04
小費            3.0
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.166297
小費比例1         NaN
Name: 49, dtype: object
總票價         12.54
小費            2.5
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.199362
小費比例1         NaN
Name: 50, dtype: object
總票價         10.29
小費            2.6
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.252672
小費比例1         NaN
Name: 51, dtype: object
總票價         34.81
小費            5.2
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.149382
小費比例1         NaN
Name: 52, dtype: object
總票價          9.94
小費           1.56
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.156942
小費比例1         NaN
Name: 53, dtype: object
總票價         25.56
小費           4.34
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.169797
小費比例1         NaN
Name: 54, dtype: object
總票價         19.49
小費           3.51
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.180092
小費比例1         NaN
Name: 55, dtype: object
總票價         38.01
小費            3.0
吸煙者           Yes
日期            Sat
時間         Dinner
大小              4
小費比例     0.078927
小費比例1         NaN
Name: 56, dtype: object
總票價         26.41
小費            1.5
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.056797
小費比例1         NaN
Name: 57, dtype: object
總票價         11.24
小費           1.76
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.156584
小費比例1         NaN
Name: 58, dtype: object
總票價         48.27
小費           6.73
吸煙者            No
日期            Sat
時間         Dinner
大小              4
小費比例     0.139424
小費比例1         NaN
Name: 59, dtype: object
總票價         20.29
小費           3.21
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.158206
小費比例1         NaN
Name: 60, dtype: object
總票價         13.81
小費            2.0
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.144823
小費比例1         NaN
Name: 61, dtype: object
總票價         11.02
小費           1.98
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.179673
小費比例1         NaN
Name: 62, dtype: object
總票價         18.29
小費           3.76
吸煙者           Yes
日期            Sat
時間         Dinner
大小              4
小費比例     0.205577
小費比例1         NaN
Name: 63, dtype: object
總票價         17.59
小費           2.64
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.150085
小費比例1         NaN
Name: 64, dtype: object
總票價         20.08
小費           3.15
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.156873
小費比例1         NaN
Name: 65, dtype: object
總票價         16.45
小費           2.47
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.150152
小費比例1         NaN
Name: 66, dtype: object
總票價          3.07
小費            1.0
吸煙者           Yes
日期            Sat
時間         Dinner
大小              1
小費比例     0.325733
小費比例1         NaN
Name: 67, dtype: object
總票價         20.23
小費           2.01
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.099357
小費比例1         NaN
Name: 68, dtype: object
總票價         15.01
小費           2.09
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.139241
小費比例1         NaN
Name: 69, dtype: object
總票價         12.02
小費           1.97
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.163894
小費比例1         NaN
Name: 70, dtype: object
總票價         17.07
小費            3.0
吸煙者            No
日期            Sat
時間         Dinner
大小              3
小費比例     0.175747
小費比例1         NaN
Name: 71, dtype: object
總票價         26.86
小費           3.14
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.116902
小費比例1         NaN
Name: 72, dtype: object
總票價         25.28
小費            5.0
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.197785
小費比例1         NaN
Name: 73, dtype: object
總票價         14.73
小費            2.2
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.149355
小費比例1         NaN
Name: 74, dtype: object
總票價         10.51
小費           1.25
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.118934
小費比例1         NaN
Name: 75, dtype: object
總票價         17.92
小費           3.08
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.171875
小費比例1         NaN
Name: 76, dtype: object
總票價          27.2
小費            4.0
吸煙者            No
日期           Thur
時間          Lunch
大小              4
小費比例     0.147059
小費比例1         NaN
Name: 77, dtype: object
總票價        22.76
小費           3.0
吸煙者           No
日期          Thur
時間         Lunch
大小             2
小費比例     0.13181
小費比例1        NaN
Name: 78, dtype: object
總票價         17.29
小費           2.71
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.156738
小費比例1         NaN
Name: 79, dtype: object
總票價         19.44
小費            3.0
吸煙者           Yes
日期           Thur
時間          Lunch
大小              2
小費比例     0.154321
小費比例1         NaN
Name: 80, dtype: object
總票價         16.66
小費            3.4
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.204082
小費比例1         NaN
Name: 81, dtype: object
總票價         10.07
小費           1.83
吸煙者            No
日期           Thur
時間          Lunch
大小              1
小費比例     0.181728
小費比例1         NaN
Name: 82, dtype: object
總票價         32.68
小費            5.0
吸煙者           Yes
日期           Thur
時間          Lunch
大小              2
小費比例     0.152999
小費比例1         NaN
Name: 83, dtype: object
總票價         15.98
小費           2.03
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.127034
小費比例1         NaN
Name: 84, dtype: object
總票價         34.83
小費           5.17
吸煙者            No
日期           Thur
時間          Lunch
大小              4
小費比例     0.148435
小費比例1         NaN
Name: 85, dtype: object
總票價         13.03
小費            2.0
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.153492
小費比例1         NaN
Name: 86, dtype: object
總票價         18.28
小費            4.0
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.218818
小費比例1         NaN
Name: 87, dtype: object
總票價         24.71
小費           5.85
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.236746
小費比例1         NaN
Name: 88, dtype: object
總票價         21.16
小費            3.0
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.141777
小費比例1         NaN
Name: 89, dtype: object
總票價         28.97
小費            3.0
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.103555
小費比例1         NaN
Name: 90, dtype: object
總票價         22.49
小費            3.5
吸煙者            No
日期            Fri
時間         Dinner
大小              2
小費比例     0.155625
小費比例1         NaN
Name: 91, dtype: object
總票價          5.75
小費            1.0
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.173913
小費比例1         NaN
Name: 92, dtype: object
總票價        16.32
小費           4.3
吸煙者          Yes
日期           Fri
時間        Dinner
大小             2
小費比例     0.26348
小費比例1        NaN
Name: 93, dtype: object
總票價         22.75
小費           3.25
吸煙者            No
日期            Fri
時間         Dinner
大小              2
小費比例     0.142857
小費比例1         NaN
Name: 94, dtype: object
總票價        40.17
小費          4.73
吸煙者          Yes
日期           Fri
時間        Dinner
大小             4
小費比例     0.11775
小費比例1        NaN
Name: 95, dtype: object
總票價         27.28
小費            4.0
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.146628
小費比例1         NaN
Name: 96, dtype: object
總票價         12.03
小費            1.5
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.124688
小費比例1         NaN
Name: 97, dtype: object
總票價         21.01
小費            3.0
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.142789
小費比例1         NaN
Name: 98, dtype: object
總票價         12.46
小費            1.5
吸煙者            No
日期            Fri
時間         Dinner
大小              2
小費比例     0.120385
小費比例1         NaN
Name: 99, dtype: object
總票價         11.35
小費            2.5
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.220264
小費比例1         NaN
Name: 100, dtype: object
總票價         15.38
小費            3.0
吸煙者           Yes
日期            Fri
時間         Dinner
大小              2
小費比例     0.195059
小費比例1         NaN
Name: 101, dtype: object
總票價          44.3
小費            2.5
吸煙者           Yes
日期            Sat
時間         Dinner
大小              3
小費比例     0.056433
小費比例1         NaN
Name: 102, dtype: object
總票價         22.42
小費           3.48
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.155219
小費比例1         NaN
Name: 103, dtype: object
總票價         20.92
小費           4.08
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.195029
小費比例1         NaN
Name: 104, dtype: object
總票價         15.36
小費           1.64
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.106771
小費比例1         NaN
Name: 105, dtype: object
總票價         20.49
小費           4.06
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.198145
小費比例1         NaN
Name: 106, dtype: object
總票價         25.21
小費           4.29
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.170171
小費比例1         NaN
Name: 107, dtype: object
總票價        18.24
小費          3.76
吸煙者           No
日期           Sat
時間        Dinner
大小             2
小費比例     0.20614
小費比例1        NaN
Name: 108, dtype: object
總票價         14.31
小費            4.0
吸煙者           Yes
日期            Sat
時間         Dinner
大小              2
小費比例     0.279525
小費比例1         NaN
Name: 109, dtype: object
總票價          14.0
小費            3.0
吸煙者            No
日期            Sat
時間         Dinner
大小              2
小費比例     0.214286
小費比例1         NaN
Name: 110, dtype: object
總票價          7.25
小費            1.0
吸煙者            No
日期            Sat
時間         Dinner
大小              1
小費比例     0.137931
小費比例1         NaN
Name: 111, dtype: object
總票價        38.07
小費           4.0
吸煙者           No
日期           Sun
時間        Dinner
大小             3
小費比例     0.10507
小費比例1        NaN
Name: 112, dtype: object
總票價         23.95
小費           2.55
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.106472
小費比例1         NaN
Name: 113, dtype: object
總票價         25.71
小費            4.0
吸煙者            No
日期            Sun
時間         Dinner
大小              3
小費比例     0.155581
小費比例1         NaN
Name: 114, dtype: object
總票價         17.31
小費            3.5
吸煙者            No
日期            Sun
時間         Dinner
大小              2
小費比例     0.202195
小費比例1         NaN
Name: 115, dtype: object
總票價         29.93
小費           5.07
吸煙者            No
日期            Sun
時間         Dinner
大小              4
小費比例     0.169395
小費比例1         NaN
Name: 116, dtype: object
總票價         10.65
小費            1.5
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.140845
小費比例1         NaN
Name: 117, dtype: object
總票價         12.43
小費            1.8
吸煙者            No
日期           Thur
時間          Lunch
大小              2
小費比例     0.144811
小費比例1         NaN
Name: 118, dtype: object
總票價         24.08
小費           2.92
吸煙者            No
日期           Thur