In [ ]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50, 5))
students_dataFrame= pd.DataFrame(scores,
            index=range(1,51),
            columns=['國文','英文','數學','地理','歷史'])
students_dataFrame

In [15]:
students_dataFrame.loc[1]

國文    60
英文    53
數學    64
地理    95
歷史    64
Name: 1, dtype: int64

In [16]:
num1_sum =np.sum(students_dataFrame.loc[1])
num1_sum

336

In [17]:
num1_average = num1_sum / 5
num1_average

67.2

In [ ]:
students_dataFrame.index.name="學號"
students_dataFrame.columns.name = "科目"
students_dataFrame

In [19]:
sums = students_dataFrame.sum(axis=1)
students_dataFrame['總分'] = sums
students_dataFrame
students_dataFrame['平均'] = sums/5
students_dataFrame

科目   國文  英文   數學   地理  歷史   總分    平均
學號
1    60  53   64   95  64  336  67.2
2    55  53   63   97  97  365  73.0
3    73  56   61  100  86  376  75.2
4   100  97   50   69  65  381  76.2
5    56  85   80   94  89  404  80.8
6    97  96   70   71  95  429  85.8
7    74  56   90  100  59  379  75.8
8    99  87   73   85  60  404  80.8
9    72  95   68   93  65  393  78.6
10   56  92   55   71  59  333  66.6
11   83  79   63   81  54  360  72.0
12   83  53   56   73  77  342  68.4
13   61  63   78   67  92  361  72.2
14   82  81   80   86  61  390  78.0
15   65  62   93   50  72  342  68.4
16   91  62   55   66  64  338  67.6
17   77  52   85   68  79  361  72.2
18   83  59   55   77  86  360  72.0
19   77  73   99   53  95  397  79.4
20   79  69   50   57  89  344  68.8
21   56  61   85   90  70  362  72.4
22   99  62   75   55  89  380  76.0
23   54  79   85   94  91  403  80.6
24   91  81   88   79  82  421  84.2
25   61  52   55   50  91  309  61.8
26   70  64   51   73  56  314  62.8
27   94  99   91   81  56  421  84.2
28   89  61   84   57  50  341  68.2
29   64  80   55   57  85  341  68.2
30   80  67   63   78  65  353  70.6
31   88  95   54   64  58  359  71.8
32   80  83  100   95  51  409  81.8
33   98  51   83   96  50  378  75.6
34   55  84   75   72  65  351  70.2
35   80  68   75   50  83  356  71.2
36   92  51   50   96  63  352  70.4
37   93  59   87   66  53  358  71.6
38   83  99   72   96  76  426  85.2
39   79  87   57   64  74  361  72.2
40   71  58   83   81  58  351  70.2
41   85  98   82   62  68  395  79.0
42   75  90   99   84  95  443  88.6
43   86  50   99   93  70  398  79.6
44   51  73   50   54  80  308  61.6
45   86  50   53   87  92  368  73.6
46   58  58   95   70  95  376  75.2
47   62  58   61   63  76  320  64.0
48   67  65   98   51  55  336  67.2
49   77  95   56   68  88  384  76.8
50   56  75   96   58  95  380  76.0

In [ ]:
students_dataFrame.to_excel('全班成績.xlsx')