In [2]:
import numpy as np
import pandas as pd

dataFrame = pd.read_csv('歷年國內主要觀光遊憩據點遊客人數月別統計.csv')
dataFrame

,年別,類型,觀光遊憩區,細分,縣市別,1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月,合計
0,2012,國家公園,陽明山國家公園,陽明山遊客中心,臺北市,12187.0,18612.0,18580.0,13329.0,14179.0,11397.0,16000.0,11791.0,10469.0,11515.0,6896.0,9631.0,154586
1,2012,國家公園,陽明山國家公園,陽明書屋,臺北市,2597.0,3617.0,5221.0,4317.0,3497.0,2815.0,3005.0,2497.0,2764.0,3701.0,2863.0,2983.0,39877
2,2012,國家公園,陽明山國家公園,陽明公園,臺北市,161000.0,463000.0,705200.0,85600.0,38600.0,28000.0,51700.0,44700.0,39000.0,36000.0,35000.0,33000.0,1720800
3,2012,國家公園,陽明山國家公園,大屯遊憩區,臺北市,17047.0,29079.0,38558.0,34332.0,43906.0,42586.0,63721.0,41881.0,51743.0,38214.0,27467.0,27306.0,455840
4,2012,國家公園,陽明山國家公園,龍鳳谷遊憩區,臺北市,21201.0,22134.0,62447.0,64691.0,16243.0,15811.0,15787.0,16963.0,16176.0,18951.0,18136.0,19135.0,307675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3060,2021,其他,-,霧峰林家園區,臺中市,17919.0,22413.0,14562.0,20850.0,6404.0,0.0,633.0,3896.0,8249.0,15638.0,NaN,NaN,110564
3061,2021,其他,-,臺中國家歌劇院,臺中市,70761.0,58994.0,72877.0,84679.0,39116.0,0.0,3508.0,33553.0,48770.0,91325.0,NaN,NaN,503583
3062,2021,其他,-,一中商圈,臺中市,1142577.0,1227190.0,1167561.0,1033384.0,415927.0,165821.0,348837.0,515960.0,651131.0,1053106.0,NaN,NaN,7721494
3063,2021,其他,-,逢甲夜市,臺中市,592042.0,672055.0,698734.0,565853.0,259384.0,93986.0,231645.0,398605.0,482115.0,658506.0,NaN,NaN,4652925
3064,2021,其他,-,潭雅神綠園道,臺中市,296840.0,405427.0,359029.0,599560.0,217254.0,0.0,267140.0,361479.0,389770.0,408215.0,NaN,NaN,3304714

In [3]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3065 entries, 0 to 3064
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年別      3065 non-null   int64
 1   類型      3065 non-null   object
 2   觀光遊憩區   3065 non-null   object
 3   細分      3065 non-null   object
 4   縣市別     3065 non-null   object
 5   1月      3064 non-null   float64
 6   2月      3064 non-null   float64
 7   3月      3064 non-null   float64
 8   4月      3064 non-null   float64
 9   5月      3064 non-null   float64
 10  6月      3064 non-null   float64
 11  7月      3064 non-null   float64
 12  8月      3064 non-null   float64
 13  9月      3064 non-null   float64
 14  10月     3064 non-null   float64
 15  11月     2741 non-null   float64
 16  12月     2741 non-null   float64
 17  合計      3065 non-null   int64
dtypes: float64(12), int64(2), object(4)
memory usage: 431.1+ KB

In [4]:
dataFrame.isna().sum()

年別         0
類型         0
觀光遊憩區      0
細分         0
縣市別        0
1月         1
2月         1
3月         1
4月         1
5月         1
6月         1
7月         1
8月         1
9月         1
10月        1
11月      324
12月      324
合計         0
dtype: int64

In [5]:
dataFrame.fillna(0,inplace=True)

In [6]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3065 entries, 0 to 3064
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年別      3065 non-null   int64
 1   類型      3065 non-null   object
 2   觀光遊憩區   3065 non-null   object
 3   細分      3065 non-null   object
 4   縣市別     3065 non-null   object
 5   1月      3065 non-null   float64
 6   2月      3065 non-null   float64
 7   3月      3065 non-null   float64
 8   4月      3065 non-null   float64
 9   5月      3065 non-null   float64
 10  6月      3065 non-null   float64
 11  7月      3065 non-null   float64
 12  8月      3065 non-null   float64
 13  9月      3065 non-null   float64
 14  10月     3065 non-null   float64
 15  11月     3065 non-null   float64
 16  12月     3065 non-null   float64
 17  合計      3065 non-null   int64
dtypes: float64(12), int64(2), object(4)
memory usage: 431.1+ KB

In [7]:
dataFrame1 = dataFrame.reindex(columns=['年別','類型','觀光遊憩區','縣市別','合計'])
dataFrame1

        年別    類型    觀光遊憩區  縣市別       合計
0     2012  國家公園  陽明山國家公園  臺北市   154586
1     2012  國家公園  陽明山國家公園  臺北市    39877
2     2012  國家公園  陽明山國家公園  臺北市  1720800
3     2012  國家公園  陽明山國家公園  臺北市   455840
4     2012  國家公園  陽明山國家公園  臺北市   307675
...    ...   ...      ...  ...      ...
3060  2021    其他        -  臺中市   110564
3061  2021    其他        -  臺中市   503583
3062  2021    其他        -  臺中市  7721494
3063  2021    其他        -  臺中市  4652925
3064  2021    其他        -  臺中市  3304714

[3065 rows x 5 columns]

In [8]:
dataFrame2=dataFrame1.set_index(['年別','類型','觀光遊憩區','縣市別'])
dataFrame3=dataFrame2.stack()
dataFrame4=dataFrame3.groupby(level=['年別','縣市別']).sum()
dataFrame4.unstack(level='年別')

年別,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
縣市別,,,,,,,,,,
南投縣,17375392,15670235,17479060,18140208,15264092,13990659,12124034,14145362,11686994,6228401
嘉義市,1345451,1842374,1756308,1634506,1700229,1693776,1621553,1444919,1323062,889369
嘉義縣,2238281,2221417,3007885,3011822,2637578,2334788,2066388,2011373,1965560,1673187
基隆市,457013,515661,625698,599293,1831341,3566559,3432720,3787328,3262697,1961908
宜蘭縣,5866140,6237217,6788605,6372632,6333843,6137323,6061359,5991095,6327960,3741283
屏東縣,8704564,8580322,10461436,10280413,7990691,6505375,5790199,22214783,5910502,3826811
彰化縣,8663509,9616743,9279571,10087420,10024417,10839080,10261441,10953409,9750807,4312579
新北市,33144677,34817421,41634076,44567057,45112001,44914675,47182862,58589767,42201746,23000302
新竹市,504292,267768,387186,362518,501218,5255181,4316148,3769606,5025939,3781699
新竹縣,14126177,10827363,12067372,12148217,12005415,11421141,10680348,11159586,11149537,5505289
桃園市,7242442,6779947,7368503,7342829,8707995,8771276,9158708,10753269,20035689,18294537
澎湖縣,1403841,1436973,1336741,1197042,1306881,1749170,1566546,2271064,2297200,894626
臺中市,16061784,37777654,39481524,40141923,39924770,42802889,44254881,44275984,45804595,40604156
臺北市,46721130,40791365,43121348,41561117,41336911,42565817,40277526,53237065,30260207,18189950
臺南市,19448188,22992345,26208334,23885426,22728341,23760941,23556369,22879056,15205263,7430008
臺東縣,3976360,3592635,4521639,3964148,4636168,4500145,4250562,5006775,6685438,3268909
花蓮縣,10979808,12103352,15376969,13033894,10748201,10003373,8981431,9813802,9615340,4822740
苗栗縣,2655330,4142331,4294931,3759231,2766895,2576024,2726827,4340185,3285629,2106727
連江縣,106756,150929,144195,156319,111281,166176,179431,194681,195447,71758
金門縣,2341493,2177649,2347337,2447966,2641295,2665624,2781357,2964966,1881768,704237
雲林縣,8629013,7568097,7511484,7723623,7364250,7396201,6309233,8748416,10193775,7765785
高雄市,29216652,32029738,30515786,28747739,32472743,31342015,33922631,34415816,22766097,10926611

In [25]:
dataFrame5 = dataFrame3.groupby(level=['年別','類型','縣市別']).sum()
dataFrame6=dataFrame5.unstack(level='類型',fill_value=0)
dataFrame6

類型        休閒農業區及休閒農場       其他      博物館    國家公園  國家級風景特定區     宗教場所    森林遊樂區  \
年別   縣市別
2012 南投縣           0  3602442        0  729862   6837870  3514481  1871971
     嘉義市           0        0   231670       0         0        0        0
     嘉義縣           0        0        0       0    157781        0  2080500
     基隆市           0    15881    52438       0    388694        0        0
     宜蘭縣           0  2203908        0       0   1068845        0   472536
...              ...      ...      ...     ...       ...      ...      ...
2021 苗栗縣      195159   921485   354299  386763         0        0        0
     連江縣           0        0        0       0     71758        0        0
     金門縣           0        0   110296  593941         0        0        0
     雲林縣           0  1361685        0       0         0  6404100        0
     高雄市           0  7173457  1615919   19285    471131  1646819        0

類型        直轄市及縣(市)級風景特定區    觀光地區
年別   縣市別
2012 南投縣          818766       0
     嘉義市         1113781       0
     嘉義縣               0       0
     基隆市               0       0
     宜蘭縣         2120851       0
...                  ...     ...
2021 苗栗縣               0  249021
     連江縣               0       0
     金門縣               0       0
     雲林縣               0       0
     高雄市               0       0

[220 rows x 9 columns]