In [3]:
import pandas_datareader.data as web
#台積電(2330.TW),聯電(2303.TW),聯發科(2454.TW),鴻海(2317.TW)
web.get_data_yahoo('2330.TW')

             High    Low   Open  Close       Volume   Adj Close
Date
2017-10-12  237.5  234.5  235.0  237.5   42390186.0  205.486588
2017-10-13  237.5  234.5  237.5  237.5   23145071.0  205.486588
2017-10-16  238.0  236.0  237.5  238.0   19964072.0  205.919174
2017-10-17  238.0  235.0  238.0  235.5   17652304.0  203.756149
2017-10-18  239.5  237.0  239.5  237.5   28886850.0  205.486588
...           ...    ...    ...    ...          ...         ...
2022-10-04  432.0  427.0  429.5  429.0   40375000.0  429.000000
2022-10-05  451.0  442.0  444.5  445.0   46496536.0  445.000000
2022-10-06  451.0  447.0  450.5  451.0   30331834.0  451.000000
2022-10-07  448.5  437.0  448.5  438.0   31941781.0  438.000000
2022-10-11  412.5  401.0  408.0  401.5  101670416.0  401.500000

[1219 rows x 6 columns]