In [1]:
import numpy as np
import pandas as pd

dataFrame = pd.read_csv('world.csv')
dataFrame.iloc[:10]

,ID,iso_code,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
0,1,AFG,亞洲,阿富汗,2020-02-24,5,5,0.000,0,0,...,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
1,2,AFG,亞洲,阿富汗,2020-02-25,5,0,0.000,0,0,...,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
2,3,AFG,亞洲,阿富汗,2020-02-26,5,0,0.000,0,0,...,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
3,4,AFG,亞洲,阿富汗,2020-02-27,5,0,0.000,0,0,...,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
4,5,AFG,亞洲,阿富汗,2020-02-28,5,0,0.000,0,0,...,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
5,6,AFG,亞洲,阿富汗,2020-02-29,5,0,0.714,0,0,...,0.0,0.0,0.0,8.33,39835428,18.6,1.337,64.83,0,99999.0
6,7,AFG,亞洲,阿富汗,2020-03-01,5,0,0.714,0,0,...,0.0,0.0,0.0,27.78,39835428,18.6,1.337,64.83,0,99999.0
7,8,AFG,亞洲,阿富汗,2020-03-02,5,0,0.000,0,0,...,0.0,0.0,0.0,27.78,39835428,18.6,1.337,64.83,0,99999.0
8,9,AFG,亞洲,阿富汗,2020-03-03,5,0,0.000,0,0,...,0.0,0.0,0.0,27.78,39835428,18.6,1.337,64.83,0,99999.0
9,10,AFG,亞洲,阿富汗,2020-03-04,5,0,0.000,0,0,...,0.0,0.0,0.0,27.78,39835428,18.6,1.337,64.83,0,99999.0

In [2]:
allDataFrame=dataFrame.reindex(columns=['洲名','國家','日期','總確診數','新增確診數','總人口數','解封指數'])
allDataFrame

        洲名   國家          日期    總確診數  新增確診數      總人口數     解封指數
0       亞洲  阿富汗  2020-02-24       5      5  39835428  99999.0
1       亞洲  阿富汗  2020-02-25       5      0  39835428  99999.0
2       亞洲  阿富汗  2020-02-26       5      0  39835428  99999.0
3       亞洲  阿富汗  2020-02-27       5      0  39835428  99999.0
4       亞洲  阿富汗  2020-02-28       5      0  39835428  99999.0
...     ..  ...         ...     ...    ...       ...      ...
187880  非洲  辛巴威  2022-07-02  255586      0  15092171  99999.0
187881  非洲  辛巴威  2022-07-03  255586      0  15092171  99999.0
187882  非洲  辛巴威  2022-07-04  255726    140  15092171  99999.0
187883  非洲  辛巴威  2022-07-05  255755     29  15092171  99999.0
187884  非洲  辛巴威  2022-07-06  255805     50  15092171  99999.0

[187885 rows x 7 columns]

In [3]:
allDataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187885 entries, 0 to 187884
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   洲名      187885 non-null  object
 1   國家      187885 non-null  object
 2   日期      187885 non-null  object
 3   總確診數    187885 non-null  int64
 4   新增確診數   187885 non-null  int64
 5   總人口數    187885 non-null  int64
 6   解封指數    187885 non-null  float64
dtypes: float64(1), int64(3), object(3)
memory usage: 10.0+ MB