In [ ]:
import numpy as np
import pandas as pd

!cat 各鄉鎮市區人口密度.csv
# !type 各鄉鎮市區人口密度.csv

In [2]:
dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame

,statistic_yyy,site_id,people_total,area,population_density
0,統計年,區域別,年底人口數,土地面積,人口密度
1,106,新北市板橋區,551480,23.1373,23835
2,106,新北市三重區,387484,16.317,23747
3,106,新北市中和區,413590,20.144,20532
4,106,新北市永和區,222585,5.7138,38956
...,...,...,...,...,...
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [3]:
#檢查
dataFrame.shape

(376, 5)

In [4]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             375 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 14.8+ KB

In [8]:
dataFrame1 = dataFrame.dropna()
dataFrame1

    statistic_yyy site_id people_total     area population_density
0             統計年     區域別        年底人口數     土地面積               人口密度
1             106  新北市板橋區       551480  23.1373              23835
2             106  新北市三重區       387484   16.317              23747
3             106  新北市中和區       413590   20.144              20532
4             106  新北市永和區       222585   5.7138              38956
..            ...     ...          ...      ...                ...
366           106  連江縣北竿鄉         2360      9.9                238
367           106  連江縣莒光鄉         1624      4.7                346
368           106  連江縣東引鄉         1352      3.8                356
369           106    東沙群島           …      2.38                 …
370           106    南沙群島           …    0.5045                 …

[371 rows x 5 columns]

In [9]:
dataFrame1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 371 entries, 0 to 370
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             371 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 17.4+ KB

In [10]:
dataFrame1['people_total'].astype(np.int32)

ValueError: invalid literal for int() with base 10: '年底人口數'

In [15]:
dataFrame2 = dataFrame1[dataFrame1['people_total'] != '年底人口數']
dataFrame2['people_total'].astype(np.int32)

ValueError: invalid literal for int() with base 10: '… '

In [22]:
dataFrame2[dataFrame2['people_total'] == "… "]
dataFrame3=dataFrame2.replace(to_replace="… ",value=0)
dataFrame3['people_total'] = dataFrame3['people_total'].astype(np.int32)
dataFrame3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       370 non-null    object
 1   site_id             370 non-null    object
 2   people_total        370 non-null    int32
 3   area                370 non-null    object
 4   population_density  370 non-null    object
dtypes: int32(1), object(4)
memory usage: 15.9+ KB

In [26]:
dataFrame3['area'] = dataFrame3['area'].astype(np.float16)
dataFrame3['population_density'] = dataFrame3['population_density'].astype(np.int32)
dataFrame3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       370 non-null    object
 1   site_id             370 non-null    object
 2   people_total        370 non-null    int32
 3   area                370 non-null    float16
 4   population_density  370 non-null    int32
dtypes: float16(1), int32(2), object(2)
memory usage: 12.3+ KB

In [27]:
#清理資料
#轉換資料
dataFrame3

    statistic_yyy site_id  people_total       area  population_density
1             106  新北市板橋區        551480  23.140625               23835
2             106  新北市三重區        387484  16.312500               23747
3             106  新北市中和區        413590  20.140625               20532
4             106  新北市永和區        222585   5.714844               38956
5             106  新北市新莊區        416524  19.734375               21102
..            ...     ...           ...        ...                 ...
366           106  連江縣北竿鄉          2360   9.898438                 238
367           106  連江縣莒光鄉          1624   4.699219                 346
368           106  連江縣東引鄉          1352   3.800781                 356
369           106    東沙群島             0   2.380859                   0
370           106    南沙群島             0   0.504395                   0

[370 rows x 5 columns]