In [1]:
#練習建立學生成績單
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目   國文  英文   數學   地理  歷史
學號
1    67  79   57   85  57
2    63  54   61   94  92
3    94  84   85   60  78
4    75  62   64   87  55
5    56  52   87   63  58
6    56  99   58   84  78
7    51  79   67   60  53
8   100  67   67   59  83
9    75  68   79   52  51
10   79  82   73   64  93
11   61  95   73   75  91
12   81  67   55   89  88
13   58  61   75   61  83
14   97  88   94   92  90
15   87  66   63   74  90
16   95  93   75   76  85
17   82  60   74   90  51
18   52  59   96   79  90
19   79  82  100   77  79
20   99  92   62   89  68
21   83  84   90   62  87
22   60  53   85   79  95
23   50  67   74   83  65
24   88  68   93   95  94
25   66  89   55   96  92
26   54  81   58   69  70
27   62  54   96   59  91
28   75  95   74   50  61
29   51  99   95   58  74
30   84  80   99   80  72
31   73  76   74  100  99
32   77  63   66   70  91
33   60  77   71   52  97
34   84  90   61   59  53
35   77  58   71   67  93
36   76  56   82   99  99
37   70  71   61   97  71
38   89  58   63   66  80
39   98  55   85   80  66
40   70  81   75   58  87
41   58  53   87   75  83
42   63  95  100   82  71
43   62  91   57   65  68
44   61  53   96   93  65
45   81  96   61   90  57
46   77  58   69   89  65
47   53  62   78   57  53
48   57  91   83   62  59
49   92  75   81   78  71
50   67  76   68   60  73

In [2]:
scores_pd.sum()

科目
國文    3625
英文    3694
數學    3773
地理    3740
歷史    3815
dtype: int64

In [3]:
scores_pd.sum(axis=1)

學號
1     345
2     364
3     401
4     343
5     316
6     375
7     310
8     376
9     325
10    391
11    395
12    380
13    338
14    461
15    380
16    424
17    357
18    376
19    417
20    410
21    406
22    372
23    339
24    438
25    398
26    332
27    362
28    355
29    377
30    415
31    422
32    367
33    357
34    347
35    366
36    412
37    370
38    356
39    384
40    371
41    356
42    411
43    343
44    368
45    385
46    358
47    303
48    352
49    397
50    344
dtype: int64

In [5]:
def myfun1(s):
    return pd.Series([s.max(),s.min(),s.median()],index=["最高分","最低分","中間分數"])

scores_pd.apply(myfun1)

科目       國文    英文     數學     地理    歷史
最高分   100.0  99.0  100.0  100.0  99.0
最低分    50.0  52.0   55.0   50.0  51.0
中間分數   74.0  75.5   74.0   75.5  78.0