In [9]:
#yahoo股票reader
#pandas_datareader
import pandas_datareader.data as web
tsmc=web.get_data_yahoo('2330.TW',start='2021-01-01',end='2021-11-10')

             High    Low   Open  Close      Volume   Adj Close
Date
2021-01-04  540.0  528.0  530.0  536.0  38770328.0  529.199768
2021-01-05  542.0  535.0  536.0  542.0  34411866.0  535.123596
2021-01-06  555.0  541.0  555.0  549.0  53030554.0  542.034790
2021-01-07  570.0  553.0  554.0  565.0  51166782.0  557.831787
2021-01-08  580.0  571.0  580.0  580.0  59563555.0  572.641541
...           ...    ...    ...    ...         ...         ...
2021-11-04  594.0  585.0  592.0  587.0  17932145.0  587.000000
2021-11-05  600.0  595.0  598.0  600.0  33270827.0  600.000000
2021-11-08  602.0  598.0  600.0  602.0  19752355.0  602.000000
2021-11-09  617.0  610.0  611.0  611.0  39538660.0  611.000000
2021-11-10  612.0  608.0  611.0  612.0  16545280.0  612.000000

[207 rows x 6 columns]